var should = require("should");

describe("Index", function() {
    var ca = `-----BEGIN CERTIFICATE-----
MIIEljCCAn4CCQC7mWYiBm7TUDANBgkqhkiG9w0BAQsFADANMQswCQYDVQQGEwJE
RTAeFw0yMDA0MTUxMTIzMzZaFw0yMzAyMDMxMTIzMzZaMA0xCzAJBgNVBAYTAkRF
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArNipcO5w9I6hV/ryyjEO
LSQJ2XzYus8vUQn8q5FIHRTnkLKPW3ti4ssFto7szH0Vj4lRTotie1uATgasviVT
wdK22WKaMFbCNKFOC5NA0rWHZfaYpT1Uzmd/AxzoFHf4UxaoOepGKN+NGXZw7Zw7
5oXpxsNebiImGAHg5a3r9kpcOCxZC/qoLYaF7fAGvSBach2R2hh2EBOSlueArmb9
5SQbMT0z3ZEH+VKiuET/RdliNhv8lSshQChgvrmAX3llMJofLr3IF8YYrBuAVRJj
j4wIZ140W0X79AExaH0xY1r+Ybp4F6AAhYS/ARBC85Nu7OeqRPHvD7UymBCTsUGB
5FS5Q+kO2UbyD349WzS36hAd14VfjiXQU9SkE9IQQDVItwvr7AlM9EE1u9Zo6Yfi
mIx6GZT0abnjXp65OQ3fP22iByxIpAa1Wsem7DJO2OcoH/g+HBySqSHYerQ/Th1s
KfXFprYyfMXkEC1G7OHc7AtUPgpVMiHE7eXUoUYcie7TOgbjH7c31rtX2Dh92u0F
ea+NHG1GC+QIo5s5XvqM19wmbWnch2nFvNxGtDOJWRDY6ukEUpoNv4kehIxvqdy7
6RglBD8WGWeAUPlML8qJGGpjUy3y4Oox0btifP/I3qWgGpGlrFiyZowLgNZKLlOz
B9yj3MqVIIkBwO/zW44/ImUCAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAGmD4TJmJ
FyeY8kwvbgj78S6p5I6q5U6A/iqz0KQHnf5SRLbAl5IYEeT1yjhbe8nt3Z4jLPT+
ENKgcyg67zvypMuXrSQfJ3UQyHp2AYcoE0cFsPNz/4dCeAJ5YS3I+sWRNkkzWx+B
DtV1UP8btsTKjB1CncL3uQ/r63NnNRj0KnCwCRdM7Y0w/q/bvgu/QSMNNY5iwajo
YBLBebcII1LebRoQ/ADjJHFInxFdpyMVdytnSTmhZh2+fP9Fehsu527aRT75QLJY
uzv1gylZR9+0ItmTsjDP87ht09cHWiIuVXoU0AWQQ/wzqc7QTv0j+8MbYVbJux9M
Tb0XwOHkkGuDTwbSC5wQA5/XBuzzQRYXIJtGfSCUVMqq5QP+VYpyp+IO3TI2/ADf
HJK8LQGTpLEz+QBKI8r7p3aYjPkaZwXPYup49koVOlrS2E7FL9k7mcHsvcEEw5DM
bNiUcBN0eIrOY6gnwTIbDe626/gNwULnUs9IpE7yiecHnyQxJL0o7/XDg3TwbOkd
5CccVAoLPQ83+0d4z/YLAZhNej0/vGdQS7gH2M52YjKlqSsrVV0If5WFjLzR3PS7
fa1ohTR0Py1pPupFf7yWoDATpqFHIy8OpZQEshaNEhFnUNCusWa0wguI5PD8ryrt
dmhZn63sQ/l3zDzSlAE/G/yz3otRccmKEnI=
-----END CERTIFICATE-----`;
    var goodCert = `-----BEGIN CERTIFICATE-----
MIID0DCCAbgCCQDmMy7ACQYw0zANBgkqhkiG9w0BAQsFADANMQswCQYDVQQGEwJE
RTAeFw0yMDA0MTUxMTI3NTVaFw0yMTA4MjgxMTI3NTVaMEcxCzAJBgNVBAYTAlVT
MQswCQYDVQQIDAJDQTEUMBIGA1UECgwLTXlPcmcsIEluYy4xFTATBgNVBAMMDG15
ZG9tYWluLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANEB0ycy
9SD9RJV6JSuCJ/+w9IJW2q99wDWzNbiNwFzxePDkFn1FV6lGicOlmfBz812Lz962
XT1WKEpSNeY/z04r8v5R6YOQ8tVJQNFdyhiRRvYwOoUNkNyxufM4T+vnOHvDh12d
j/76sH1BZQl+OHADrFHafwjgrWYvcuvhcWesFUzCqqY6LekD/fh5U5y4KUwspcZl
GZRVfNB6r5tHYX65kVZB+MZs5Jr8MVVNHyrXwkVkIY+XE3WdszlWWD4bEdCy+S8Y
20Lv17MebImv8QCAgvfNai7kwy5OYxqKQiHeTkbyBeJlHQ/gzGF8bZtq2FRjubFD
KdTs3x26rGR1zsECAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAWgt4ch44rKupW1kj
0jvy8ViNg4itakGTOzP4jl/sJLo6gz77zOaKdHx0XI0x0S+xgars/0bXFMxdZZPa
2WD6SV1kBFOM/p3+wm6WLpKKTK7bnUmoB5ig7IovjZtNtcSLaRuzdkX91gejg1xM
4WFZAaaUI9Xe87Qtm3XbIYMoY+Fpsk1SKgAxw0PtysVFJAkI2Vl2+tfIb5PguHK+
TKUKan7cn9jWNRot7ylmk7XpR4OkNzkICwswDlrUrxqsiXirDki0A70FtY4DcxM3
bcBv0ZrdvojI69DhXzCHMeBPge/RB1cMzYAsVDcAO1Fs2G9iMdNotYycV44j0MiC
DjgvtPIqGANjPPSyQPF9vW4sWOKcCUBIlcT4fz3cgKjFGnW4SHKqYtNNJ5KFiwWp
UjRlwjgnvrfpRcSTwxZSeEgsrbMPJi/YEPrGKJxoxP4DKw8ttokY+VAQCyTPF3Iz
NOUeNFjs9kqiPlYFG+OEG2Zqj2/TrGmpjLsgVbSX/UCF+tlAgWQrc70OH0PlDgrk
7vRMDujCafh7uTlhpgZ7+wa4gm/ek2VBo8Eslvg9I2PW6eHCBJ72haA3yoxLK6/E
M8hXP1AQSMh3L/vxmPigbhK+L3/JD+1csjdrPADCufN+piPJNrCVhiBPdnOUggSC
CK5w0S9unWoNxfo2TZcJ0Aepl7E=
-----END CERTIFICATE-----`;

var badCert = "-----BEGIN CERTIFICATE-----\n"+
"MIIDejCCAmICAQEwDQYJKoZIhvcNAQELBQAwgYAxCzAJBgNVBAYTAkNOMRIwEAYD\n"+
"VQQIDAlHdWFuZ2RvbmcxEjAQBgNVBAcMCUd1YW5nemhvdTEMMAoGA1UECgwDR1pD\n"+
"MQswCQYDVQQLDAJJVDELMAkGA1UEAwwCQ0ExITAfBgkqhkiG9w0BCQEWEmJlZXZl\n"+
"bkBob3RtYWlsLmNvbTAeFw0xNjAxMTEwNzA5MjRaFw0xNjAyMTAwNzA5MjRaMIGE\n"+
"MQswCQYDVQQGEwJDTjESMBAGA1UECAwJR3Vhbmdkb25nMRIwEAYDVQQHDAlHdWFu\n"+
"Z3pob3UxDDAKBgNVBAoMA0daQzELMAkGA1UECwwCSVQxDzANBgNVBAMMBlNlcnZl\n"+
"cjEhMB8GCSqGSIb3DQEJARYSYmVldmVuQGhvdG1haWwuY29tMIIBIjANBgkqhkiG\n"+
"9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuF5DGz5pCniKcOWpJGXiTrZz030ixko4ztFF\n"+
"LF+RIYyE78ux62UuTgWIJdVrriPutwNNkYqYBj5E+tEEjyOIx7C6qZGmRQp5Gp6E\n"+
"V9i2SipA/0Jr0CFN+M1hdOG8LyIxv/LNxoHQeT9pIGdKqGd5qrTQ4UiyeEb+Qzjb\n"+
"Dr73rFRAwQuClPGARcWQRWQ8x2PrcDPeF6IvqmvGu1v4v9PxEkkUzM322F7fCNoC\n"+
"aWl4u1A1ayq5dewm7LzNY5JVhqtTJaMacc2I9yntsf7bytx91soKO2+xFoNNSjbY\n"+
"xsCFUF0XEOTEyPZLFyx3qrXIQY79/Pi20n5bHZuBgTGsd5ESrwIDAQABMA0GCSqG\n"+
"SIb3DQEBCwUAA4IBAQAfHjiyC35/xJDD6SzwXn7wIYUq0xyCXuNnYPvmIUwOJibC\n"+
"7feMriVL8P/HWDjef8EX/cDEDgUnDTGcPYR3e3pO3idroFWFkNGgpHyUX1c+g3Xt\n"+
"21ShU0M1R6azEtJV9UN7W/xpBkuv9FJsYDof/7TK9g0uuXgsCK2501ln2jEXEB/+\n"+
"GB+bZMbLuzQkKQXIFqZz1SktYU+VyT+4OIvolBytfUhNUSztt7YcxuLVsXoiBzFh\n"+
"87g2I+8TEPDWyebSWoyWP70g/42zmNybel+snjlYIjSM10HM4jJg4yQYu4xe/t4m\n"+
"bnpNaaue+EKc79B25yIJdxLIw03CcreT6ROArgnr"+
"\n-----END CERTIFICATE-----";

var chainCACert = `-----BEGIN CERTIFICATE-----
MIIE0zCCA7ugAwIBAgIQGNrRniZ96LtKIVjNzGs7SjANBgkqhkiG9w0BAQUFADCB
yjELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL
ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJp
U2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxW
ZXJpU2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0
aG9yaXR5IC0gRzUwHhcNMDYxMTA4MDAwMDAwWhcNMzYwNzE2MjM1OTU5WjCByjEL
MAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQLExZW
ZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJpU2ln
biwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxWZXJp
U2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0aG9y
aXR5IC0gRzUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvJAgIKXo1
nmAMqudLO07cfLw8RRy7K+D+KQL5VwijZIUVJ/XxrcgxiV0i6CqqpkKzj/i5Vbex
t0uz/o9+B1fs70PbZmIVYc9gDaTY3vjgw2IIPVQT60nKWVSFJuUrjxuf6/WhkcIz
SdhDY2pSS9KP6HBRTdGJaXvHcPaz3BJ023tdS1bTlr8Vd6Gw9KIl8q8ckmcY5fQG
BO+QueQA5N06tRn/Arr0PO7gi+s3i+z016zy9vA9r911kTMZHRxAy3QkGSGT2RT+
rCpSx4/VBEnkjWNHiDxpg8v+R70rfk/Fla4OndTRQ8Bnc+MUCH7lP59zuDMKz10/
NIeWiu5T6CUVAgMBAAGjgbIwga8wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E
BAMCAQYwbQYIKwYBBQUHAQwEYTBfoV2gWzBZMFcwVRYJaW1hZ2UvZ2lmMCEwHzAH
BgUrDgMCGgQUj+XTGoasjY5rw8+AatRIGCx7GS4wJRYjaHR0cDovL2xvZ28udmVy
aXNpZ24uY29tL3ZzbG9nby5naWYwHQYDVR0OBBYEFH/TZafC3ey78DAJ80M5+gKv
MzEzMA0GCSqGSIb3DQEBBQUAA4IBAQCTJEowX2LP2BqYLz3q3JktvXf2pXkiOOzE
p6B4Eq1iDkVwZMXnl2YtmAl+X6/WzChl8gGqCBpH3vn5fJJaCGkgDdk+bW48DW7Y
5gaRQBi5+MHt39tBquCWIMnNZBU4gcmU7qKEKQsTb47bDN0lAtukixlE0kF6BWlK
WE9gyn6CagsCqiUXObXbf+eEZSqVir2G3l6BFoMtEMze/aiCKm0oHw0LxOXnGiYZ
4fQRbxC1lfznQgUy286dUV4otp6F01vvpX1FQHKOtw5rDgb7MzVIcbidJ4vEZV8N
hnacRHr2lVz2XTIIM6RUthg/aFzyQkqFOFSDX9HoLPKsEdao7WNq
-----END CERTIFICATE-----`;

var chainIntermediaryCert = `-----BEGIN CERTIFICATE-----
MIIFODCCBCCgAwIBAgIQUT+5dDhwtzRAQY0wkwaZ/zANBgkqhkiG9w0BAQsFADCB
yjELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL
ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJp
U2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxW
ZXJpU2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0
aG9yaXR5IC0gRzUwHhcNMTMxMDMxMDAwMDAwWhcNMjMxMDMwMjM1OTU5WjB+MQsw
CQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAdBgNV
BAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVjIENs
YXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAstgFyhx0LbUXVjnFSlIJluhL2AzxaJ+aQihiw6UwU35VEYJb
A3oNL+F5BMm0lncZgQGUWfm893qZJ4Itt4PdWid/sgN6nFMl6UgfRk/InSn4vnlW
9vf92Tpo2otLgjNBEsPIPMzWlnqEIRoiBAMnF4scaGGTDw5RgDMdtLXO637QYqzu
s3sBdO9pNevK1T2p7peYyo2qRA4lmUoVlqTObQJUHypqJuIGOmNIrLRM0XWTUP8T
L9ba4cYY9Z/JJV3zADreJk20KQnNDz0jbxZKgRb78oMQw7jW2FUyPfG9D72MUpVK
Fpd6UiFjdS8W+cRmvvW1Cdj/JwDNRHxvSz+w9wIDAQABo4IBYzCCAV8wEgYDVR0T
AQH/BAgwBgEB/wIBADAwBgNVHR8EKTAnMCWgI6Ahhh9odHRwOi8vczEuc3ltY2Iu
Y29tL3BjYTMtZzUuY3JsMA4GA1UdDwEB/wQEAwIBBjAvBggrBgEFBQcBAQQjMCEw
HwYIKwYBBQUHMAGGE2h0dHA6Ly9zMi5zeW1jYi5jb20wawYDVR0gBGQwYjBgBgpg
hkgBhvhFAQc2MFIwJgYIKwYBBQUHAgEWGmh0dHA6Ly93d3cuc3ltYXV0aC5jb20v
Y3BzMCgGCCsGAQUFBwICMBwaGmh0dHA6Ly93d3cuc3ltYXV0aC5jb20vcnBhMCkG
A1UdEQQiMCCkHjAcMRowGAYDVQQDExFTeW1hbnRlY1BLSS0xLTUzNDAdBgNVHQ4E
FgQUX2DPYZBV34RDFIpgKrL1evRDGO8wHwYDVR0jBBgwFoAUf9Nlp8Ld7LvwMAnz
Qzn6Aq8zMTMwDQYJKoZIhvcNAQELBQADggEBAF6UVkndji1l9cE2UbYD49qecxny
H1mrWH5sJgUs+oHXXCMXIiw3k/eG7IXmsKP9H+IyqEVv4dn7ua/ScKAyQmW/hP4W
Ko8/xabWo5N9Q+l0IZE1KPRj6S7t9/Vcf0uatSDpCr3gRRAMFJSaXaXjS5HoJJtG
QGX0InLNmfiIEfXzf+YzguaoxX7+0AjiJVgIcWjmzaLmFN5OUiQt/eV5E1PnXi8t
TRttQBVSK/eHiXgSgW7ZTaoteNTCLD0IX4eRnh8OsN4wUmSGiaqdZpwOdgyA8nTY
Kvi4Os7X1g8RvmurFPW9QaAiY4nxug9vKWNmLT+sjHLF+8fk1A/yO0+MKcc=
-----END CERTIFICATE-----`;

var chainServerCert = `-----BEGIN CERTIFICATE-----
MIIFfjCCBGagAwIBAgIQPyXKruWqg4+pHAUadfxxnTANBgkqhkiG9w0BAQsFADB+
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVj
IENsYXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MB4XDTE2MTAwNzAwMDAwMFoX
DTE3MTAzMDIzNTk1OVowbTELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0
b24xEDAOBgNVBAcMB1NlYXR0bGUxGTAXBgNVBAoMEEFtYXpvbi5jb20sIEluYy4x
HDAaBgNVBAMME2VjaG8tYXBpLmFtYXpvbi5jb20wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQCcr7MGu5EDVOduBAbET5vheJNNnIOQbAnrTrwAaxdCaC32
VWELwJNMLjB1Hk1eixuhXr/rfCitAI2jjXZywFWNTLcfX9USz7kq/4CIA5S4qgF8
RTzMC8cJzsaY4pSA2J1wMDQxKnHdlMxIYZuR9ouKRHOd7qcVnqM06eSpO0YPpKsI
hiAs0CtJxig/MhxcTKkcWuiCfOtHgR7Rhx58ZnJLzVip6/+WWLTV0CBG+mcC3Lry
thObGQ2HNRIboghsUcjFckoARMCQaIolyBml8bbU6TkOTfIasRJj8gPk6fG8zGJd
KdfCG3wkPpt3Xm6LS08NrzkHSOlkuWipBl7bqhGjAgMBAAGjggIHMIICAzAeBgNV
HREEFzAVghNlY2hvLWFwaS5hbWF6b24uY29tMAkGA1UdEwQCMAAwDgYDVR0PAQH/
BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBhBgNVHSAEWjBY
MFYGBmeBDAECAjBMMCMGCCsGAQUFBwIBFhdodHRwczovL2Quc3ltY2IuY29tL2Nw
czAlBggrBgEFBQcCAjAZDBdodHRwczovL2Quc3ltY2IuY29tL3JwYTAfBgNVHSME
GDAWgBRfYM9hkFXfhEMUimAqsvV69EMY7zArBgNVHR8EJDAiMCCgHqAchhpodHRw
Oi8vc3Muc3ltY2IuY29tL3NzLmNybDBXBggrBgEFBQcBAQRLMEkwHwYIKwYBBQUH
MAGGE2h0dHA6Ly9zcy5zeW1jZC5jb20wJgYIKwYBBQUHMAKGGmh0dHA6Ly9zcy5z
eW1jYi5jb20vc3MuY3J0MA8GAytlTQQIMAYCAQECAQEwgYsGCisGAQQB1nkCBAIE
fQR7AHkAdwCnzkpOYgfgrd7l/apLH4Z2h2e10AKlXUcxDn5nCpXqsgAAAVefqkBK
AAAEAwBIMEYCIQDKa3wGnBQLd06NZO2V1KWekjSeBKo8cbME8yx0vIV/gQIhAPoV
LPhVi6Coe1Fat1ItG+FyV0DhKAQjCd0nT+6l6ztiMA0GCSqGSIb3DQEBCwUAA4IB
AQB7hqbnqGsZJXk4AQi36tocJeKIq0YSARfcaoBjUyTIlxPHAgbvP+E8yl7f9DYB
lyy5ZliCatzWiw+zrn9WB9A21q6K+CTNltfxtNtY5xQ0MDHykrF+bu+DhyoP1YbM
DR2oWmd+SrTGVA6RMrW8VkRTPgOI+DCxtnV7fbiKuChG8Is7bc7H8kMZq36lb4ZZ
Ld3sRSLK8zHIuBpOVD+9v01mG1NLrlRkZduIpSW8gqe0En8K/0pVUlknpmoJBVdD
8QnjDZDKB00lgWbw5HLLfM2wdHredPcEDP7rmnjDSDhkxRBtVCVWyHSvdoAFpuyD
resu4y+Ob3GCo2J3XCv0Cvog
-----END CERTIFICATE-----`;

    var plugin = require("../");
    it("should return 1 if certificates are valid", function(done) {
        plugin.verifyCert(goodCert, ca,function(err,ret){
            should(err).be.Null();
            ret.should.equal(1);
            done();
        });
    });

    it("should return 0 if cert is not valid", function(done) {
        plugin.verifyCert(badCert, ca,function(err,ret){
            ret.should.equal(0);
            err.should.not.be.Null();
            done()
        });
    });

    it("should return 0 if a chain of certificates are not valid", function(done) {
        // Missing the CA cert
        var ca = chainIntermediaryCert;
        plugin.verifyCert(chainServerCert, ca,function(err,ret) {
            ret.should.equal(0);
            err.should.not.be.Null();

            // Missing the intermediary cert
            ca = chainCACert;
            plugin.verifyCert(chainServerCert, ca,function(err,ret) {
                ret.should.equal(0);
                err.should.not.be.Null();
                done();
            });
        });
    });

    it("should return a promise if no callback", function(done){
        var p = plugin.verifyCert(goodCert,ca);
        p.should.be.a.Promise();
        p.then(function(result){
            result.should.equal(1);
            done();
        },function(err){
            done(err);
        })
    });

    it("should return a promise which is rejected with an error if certificate is not valid.", function(done){
        var p = plugin.verifyCert(badCert,ca);
        p.then(function(result){
            done("Should not be here");
        },function(err){
            err.should.not.be.Null();
            done();
        })
    });
})
